name: Publish GKE Infra

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Target environment
        required: true
        type: choice
        options: [dev, prod]
        default: dev
      apply:
        description: Apply Terraform (true) or plan only (false)
        required: true
        type: boolean
        default: false
      # destroy:
      #   description: destroy Terraform resources after apply (true or false)
      #   required: true
      #   type: boolean
      #   default: false
      # tf_dir:                    # <— NEW: path to your TF folder
      #   description: "Terraform directory (repo-relative)"
      #   required: true
      #   default: "infra/gcp"     # change to e.g. "snowflake/terraform" if that’s your layout

jobs:
  gke-infra:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        working-directory: infra/gcp
        run: |
          terraform init -upgrade -reconfigure
          terraform validate

      - name: Terraform Plan
        working-directory: infra/gcp
        run: |
          terraform plan -input=false -no-color \
            -var-file="envs/${{ github.event.inputs.environment }}.tfvars"

      - name: Terraform Apply
        if: ${{ github.event.inputs.apply == 'true' }}
        working-directory:  infra/gcp
        run: |
          terraform apply -auto-approve -input=false -no-color \
            -var-file="envs/${{ github.event.inputs.environment }}.tfvars"
      
      # - name: Terraform Destroy
      #   if: ${{ github.event.inputs.apply == 'true' }}
      #   working-directory:  infra/gcp
      #   run: |
      #     terraform destroy -auto-approve -input=false -no-color \
      #       -var-file="envs/${{ github.event.inputs.environment }}.tfvars"

